import json
import os
from datetime import date

out_path = r"docs/claude-cowork/ielts-hourly-practice-tool/data/chatgpt/bbc/bbc-gpt-220602-platinum-jubilee.json"
os.makedirs(os.path.dirname(out_path), exist_ok=True)

title = "Queen Elizabeth II: What is the Platinum Jubilee?"

def p(en, vi):
    return f'<p class="en">{en}</p><p class="vi">{vi}</p>'

obj = {
    "schema": 2,
    "format": "bbc-6min",
    "id": "bbc-gpt-220602-platinum-jubilee",
    "type": "lesson",
    "source": "chatgpt",
    "category": "bbc-6-minute-english",
    "topicNumber": 0,
    "title": title,
    "titleVi": "Nữ hoàng Elizabeth II: Kỷ niệm Bạch kim là gì?",
    "band": "7.0-8.0",
    "dateTime": "2022-06-02T00:00",
    "dialogueMode": "original",
    "episode": {
        "id": "ep-220602",
        "date": "2022-06-02",
        "title": title,
        "url": "https://www.bbc.co.uk/learningenglish/english/features/6-minute-english_2022/ep-220602",
        "savedAt": str(date.today()),
    },
    "links": {
        "bbc": "https://www.bbc.co.uk/learningenglish/english/features/6-minute-english_2022/ep-220602",
        "transcript": "http://downloads.bbc.co.uk/learningenglish/features/6min/220602_6min_english_jubilee.pdf",
        "sounds": "https://www.bbc.co.uk/sounds",
        "spotify": "https://open.spotify.com/search/BBC%206%20Minute%20English%20Queen%20Elizabeth%20II%20What%20is%20the%20Platinum%20Jubilee",
    },
    "summary": {
        "en": [
            "This episode explains the meaning of a jubilee and uses Queen Elizabeth II's Platinum Jubilee to explore long reigns, royal celebrations, and the tradition of creating special commemorative foods.",
            "The programme also introduces vocabulary such as reign, coronation, trifle, twist on something, and humble, all in a light and practical way for IELTS learners.",
        ],
        "vi": [
            "Tập này giải thích ý nghĩa của từ jubilee và dùng Lễ kỷ niệm Bạch kim của Nữ hoàng Elizabeth II để khám phá các triều đại dài lâu, lễ mừng hoàng gia, và truyền thống tạo ra những món ăn kỷ niệm đặc biệt.",
            "Chương trình cũng giới thiệu các từ vựng như reign, coronation, trifle, twist on something và humble theo cách nhẹ nhàng, thực tế cho người học IELTS.",
        ],
    },
    "words": ["jubilee", "reign", "coronation", "trifle", "twist", "humble", "commemorate"],
    "sections": [],
}

vocab = [
    ("jubilee", "/ˈdʒuːbɪli/", "lễ kỷ niệm lớn", "A celebration of an anniversary, especially a royal anniversary.", "The country held a jubilee to mark the monarch's long reign.", "In IELTS Speaking Part 2, you can say: \"The event felt like a true <strong>jubilee</strong> for the whole town.\""),
    ("reign", "/reɪn/", "triều đại; thời gian trị vì", "The period of time when a king or queen rules a country.", "Elizabeth II had the longest reign in British history.", "In IELTS Writing, you can write: \"A long <strong>reign</strong> often becomes part of a nation's identity.\""),
    ("coronation", "/ˌkɒrəˈneɪʃn/", "lễ đăng quang", "The ceremony at which someone is made king or queen.", "The coronation took place in a grand cathedral.", "In IELTS Speaking Part 3, you might say: \"A coronation can symbolise continuity and national unity.\""),
    ("trifle", "/ˈtraɪfl/", "món tráng miệng nhiều lớp", "A sweet cold dessert made with cake, fruit, custard, and cream.", "The family shared a large trifle after dinner.", "In IELTS Speaking Part 1, you can say: \"I rarely make dessert, but I can prepare a simple <strong>trifle</strong>.\""),
    ("twist", "/twɪst/", "biến tấu; cách tân", "A new variation of something traditional.", "This recipe is a modern twist on a classic pudding.", "In IELTS Writing, you can write: \"The film offers a clever <strong>twist</strong> on a familiar story.\""),
    ("humble", "/ˈhʌmbl/", "khiêm tốn", "Modest and not proud.", "She gave a humble answer despite winning the competition.", "In IELTS Speaking Part 2, you can say: \"A <strong>humble</strong> attitude usually makes people easier to trust.\""),
    ("commemorate", "/kəˈmeməreɪt/", "kỷ niệm, tưởng nhớ", "To do something special to remember an important event.", "People commemorated the occasion with street parties.", "In IELTS Writing, you can write: \"Nations often <strong>commemorate</strong> important milestones with public celebrations.\""),
]

vocab_html = []
for word, ipa, vi, definition, example, ielts in vocab:
    vocab_html.append(
        f'<div class="vocab-card"><div class="vocab-header"><span class="vocab-word">{word}</span><span class="vocab-ipa">{ipa}</span><span class="vocab-vi-meaning vi">{vi}</span></div>'
        f'<div class="vocab-row"><span class="vocab-label">Definition</span><div class="vocab-content">{p(definition, "Bản dịch ý nghĩa.")}</div></div>'
        f'<div class="vocab-row"><span class="vocab-label">Example</span><div class="vocab-content">{p(example.replace(word, f"<strong>{word}</strong>"), "Ví dụ tương ứng bằng tiếng Việt.")}</div></div>'
        f'<div class="vocab-row ielts-row"><span class="vocab-label">IELTS</span><div class="vocab-content">{p(ielts, "Câu ứng dụng cho IELTS.")}</div></div></div>'
    )
obj["sections"].append({"id": "vocab", "title": "Vocabulary", "level": 1, "html": " ".join(vocab_html)})

dialogue = (
    '<div class="disclaimer"><p class="en">This dialogue follows the official BBC episode transcript with Vietnamese translation for study.</p>'
    '<p class="vi">Hội thoại này theo bản ghi chính thức của tập BBC, kèm bản dịch tiếng Việt phục vụ học tập.</p>'
    '<p class="en"><a class="ext-link" href="http://downloads.bbc.co.uk/learningenglish/features/6min/220602_6min_english_jubilee.pdf" target="_blank" rel="noopener">↗ View original transcript (PDF)</a></p>'
    '<p class="vi">↗ Xem bản ghi gốc (PDF)</p></div>'
)

turns = [
    ("Presenter", [("Hello. This is 6 Minute English from BBC Learning English.", "Xin chào. Đây là 6 Minute English từ BBC Learning English."), ("I'm Neil.", "Tôi là Neil.")]),
    ("Co-presenter", [("And I'm Sam.", "Và tôi là Sam."), ("People in the UK are enjoying a four-day holiday as part of the celebrations for Queen Elizabeth II's Platinum Jubilee.", "Người dân ở Vương quốc Anh đang tận hưởng kỳ nghỉ bốn ngày như một phần của các hoạt động mừng Đại lễ Bạch kim của Nữ hoàng Elizabeth II.")]),
    ("Co-presenter", [("A jubilee celebrates the anniversary of a special event, and the word is mostly associated with the Royal Family.", "Jubilee là lễ kỷ niệm một sự kiện đặc biệt, và từ này thường gắn với Hoàng gia."), ("In 2022, Queen Elizabeth II celebrates her Platinum Jubilee, commemorating 70 years since she became Queen in 1952.", "Năm 2022, Nữ hoàng Elizabeth II kỷ niệm Đại lễ Bạch kim, đánh dấu 70 năm kể từ khi bà trở thành Nữ hoàng vào năm 1952.")]),
    ("Presenter", [("People are doing all kinds of things to celebrate, from large events at Buckingham Palace and St Paul's Cathedral, to smaller street parties in towns and cities up and down the country, and abroad.", "Mọi người đang tổ chức đủ loại hoạt động để ăn mừng, từ các sự kiện lớn tại Cung điện Buckingham và Nhà thờ St Paul, đến những bữa tiệc đường phố nhỏ hơn ở các thị trấn và thành phố khắp đất nước, và cả ở nước ngoài."), ("In this programme, we look at the Platinum Jubilee in an unusual way, by hearing about a cake competition to make the official jubilee cake - the Platinum Pudding.", "Trong chương trình này, chúng ta nhìn vào Đại lễ Bạch kim theo một cách khác thường, bằng cách nghe về cuộc thi làm món bánh chính thức của lễ kỷ niệm - Platinum Pudding."), ("And, as usual, we'll be learning some related vocabulary as well.", "Và như thường lệ, chúng ta cũng sẽ học một số từ vựng liên quan.")]),
    ("Co-presenter", [("This isn't the first celebration of Queen Elizabeth's reign - the period of time when a monarch rules a country.", "Đây không phải là lần đầu tiên trong triều đại của Nữ hoàng Elizabeth - tức là khoảng thời gian một quân vương trị vì một đất nước."), ("In 1977, the Queen celebrated her Silver Jubilee, marking 25 years as queen, followed by her Golden Jubilee in 2002, and her Diamond Jubilee in 2012.", "Năm 1977, Nữ hoàng đã mừng Silver Jubilee, đánh dấu 25 năm làm Nữ hoàng, tiếp theo là Golden Jubilee vào năm 2002 và Diamond Jubilee vào năm 2012.")]),
    ("Presenter", [("But what's so special about this year's Platinum Jubilee is that Queen Elizabeth II is the first British monarch ever to spend 70 years on the throne.", "Nhưng điều đặc biệt của Đại lễ Bạch kim năm nay là Nữ hoàng Elizabeth II là vị quân vương Anh đầu tiên từng trị vì 70 năm trên ngai vàng."), ("And I have a question about it, Sam.", "Và tôi có một câu hỏi về điều này, Sam."), ("Queen Elizabeth II is Britain's longest-ever reigning monarch, but who was the previous longest-reigning before her?", "Nữ hoàng Elizabeth II là quân vương trị vì lâu nhất trong lịch sử nước Anh, nhưng ai là người giữ kỷ lục này trước bà?"), ("Was it: a) Henry VIII? b) Elizabeth I? or c) Queen Victoria?", "Đó là: a) Henry VIII? b) Elizabeth I? hay c) Queen Victoria?")]),
    ("Co-presenter", [("I know it's c) Queen Victoria.", "Tôi biết đó là c) Queen Victoria.")]),
    ("Presenter", [("OK. I'll reveal the answer at the end of the programme.", "Được rồi. Tôi sẽ công bố đáp án vào cuối chương trình."), ("As the first monarch ever to have a platinum jubilee, many celebrations are being planned for the Queen.", "Là vị quân vương đầu tiên từng có đại lễ bạch kim, rất nhiều hoạt động kỷ niệm đang được lên kế hoạch cho Nữ hoàng.")]),
    ("Presenter", [("These include an official birthday parade, Trooping the Colour, which ends with jet planes flying over Buckingham Palace, and the Platinum Pageant - a live concert in front of the palace, featuring music and dancing, puppets of the Queen's favourite pets - her corgi dogs - and a performance by Ed Sheeran.", "Trong số đó có cuộc diễu hành sinh nhật chính thức, Trooping the Colour, kết thúc bằng màn máy bay phản lực bay qua Cung điện Buckingham, và Platinum Pageant - một buổi hòa nhạc trực tiếp trước cung điện, với âm nhạc, khiêu vũ, những con rối mô phỏng các thú cưng yêu thích của Nữ hoàng - những chú chó corgi - và phần trình diễn của Ed Sheeran.")]),
    ("Co-presenter", [("And that's just in London.", "Và đó mới chỉ là ở London."), ("All across the UK street parties are being held for people to eat and drink with friends and neighbours.", "Khắp nước Anh, các bữa tiệc đường phố đang được tổ chức để mọi người ăn uống cùng bạn bè và hàng xóm."), ("There's a tradition of inventing a new food dish to commemorate jubilees, going all the way back to the Victoria sponge, a cake named after Queen Victoria.", "Có một truyền thống là sáng tạo ra món ăn mới để kỷ niệm các dịp jubilee, bắt đầu từ bánh Victoria sponge - một loại bánh được đặt theo tên Nữ hoàng Victoria."), ("This year a competition was held to find a new dish to become the official pudding of the jubilee.", "Năm nay, một cuộc thi đã được tổ chức để tìm ra món ăn mới trở thành món pudding chính thức của lễ kỷ niệm."), ("Here's BBC reporter, Daniella Relph, to explain more.", "Sau đây là phóng viên BBC để giải thích thêm.")]),
    ("Reporter", [("First, there was the Victoria sponge, then coronation chicken, now we have a Queen Elizabeth II Platinum Pudding.", "Đầu tiên là Victoria sponge, rồi đến coronation chicken, và giờ là Queen Elizabeth II Platinum Pudding."), ("The winning lemon Swiss roll and amaretti trifle is a twist on a traditional trifle, with layers of Swiss roll, jelly, custard, mandarins, amaretti biscuits and cream.", "Món lemon Swiss roll và amaretti trifle chiến thắng là một biến tấu của món trifle truyền thống, với các lớp Swiss roll, thạch, sữa trứng, quýt, bánh amaretti và kem.")]),
    ("Presenter", [("In 1953, a mix of chicken and curry cream sauce called, coronation chicken, was invented to celebrate Queen Elizabeth's coronation - the ceremony at which she was made queen.", "Năm 1953, món ăn gồm gà và sốt kem cà ri gọi là coronation chicken đã được tạo ra để mừng lễ đăng quang của Nữ hoàng Elizabeth - buổi lễ mà bà chính thức được phong làm Nữ hoàng.")]),
    ("Co-presenter", [("This year, competition winner, Jemma Melvin, has invented a lemon and Swiss roll amaretti trifle as the official jubilee cake.", "Năm nay, người thắng cuộc thi, Jemma Melvin, đã sáng tạo ra một món trifle vị chanh, Swiss roll và amaretti làm bánh chính thức cho lễ kỷ niệm."), ("Trifle is a sweet, cold pudding made of three layers - a layer of fruit and cake, a layer of custard, and a top layer of cream.", "Trifle là món tráng miệng ngọt, lạnh, gồm ba lớp - một lớp trái cây và bánh, một lớp sữa trứng, và lớp trên cùng là kem.")]),
    ("Presenter", [("Jemma's jubilee trifle is a twist on a traditional trifle.", "Món trifle mừng jubilee của Jemma là một biến tấu của món trifle truyền thống."), ("When talking about food, people use the phrase a twist on something to describe a new variation of a traditional recipe, using different, exciting ingredients.", "Khi nói về đồ ăn, người ta dùng cụm a twist on something để chỉ một biến thể mới của một công thức truyền thống, sử dụng những nguyên liệu khác biệt và thú vị.")]),
    ("Co-presenter", [("Jemma learned her winning recipe from her grandmothers.", "Jemma đã học công thức chiến thắng từ các bà của mình."), ("She wants her trifle to be “the people's pudding”, something to be enjoyed by everyone.", "Cô ấy muốn món trifle của mình trở thành “món pudding của mọi người”, tức là món ai cũng có thể thưởng thức."), ("Here is Jemma Melvin describing how she felt to discover her trifle had been chosen as the official Platinum Pudding:", "Sau đây là Jemma Melvin kể lại cảm giác của cô khi biết món trifle của mình được chọn làm Platinum Pudding chính thức:")]),
    ("Guest expert", [("I cannot believe it!", "Tôi không thể tin được!"), ("Everything that I was up against was just the most beautiful desserts and pudding with beautiful stories.", "Mọi thứ tôi phải cạnh tranh đều là những món tráng miệng và pudding đẹp nhất với những câu chuyện thật đẹp."), ("That this quite humble trifle has won is a bit surreal.", "Việc món trifle khá khiêm tốn này chiến thắng thật sự có chút phi thực tế.")]),
    ("Presenter", [("Jemma describes her trifle as humble - modest, and not proud.", "Jemma mô tả món trifle của mình là humble - khiêm tốn, không kiêu ngạo."), ("Although the pudding contains ingredients like amaretti biscuits and cream, which are good enough for a queen, she wanted to base it on a humble trifle, something everyone around the country can make.", "Dù món pudding có các nguyên liệu như bánh amaretti và kem, vốn đủ sang trọng cho một Nữ hoàng, cô vẫn muốn xây dựng nó dựa trên một món trifle khiêm tốn, thứ mà mọi người trên khắp đất nước đều có thể làm.")]),
    ("Co-presenter", [("Enjoying a bowl of Jemma's Platinum Pudding sounds like a great way for some to celebrate the Queen's seventy-year reign.", "Thưởng thức một bát Platinum Pudding của Jemma nghe có vẻ là cách tuyệt vời để nhiều người mừng triều đại 70 năm của Nữ hoàng.")]),
    ("Presenter", [("Which reminds me of your question, Neil.", "Điều đó làm tôi nhớ đến câu hỏi của anh, Neil."), ("We know Elizabeth II has reigned for 70 years, but who was the second longest-serving monarch?", "Chúng ta biết Elizabeth II đã trị vì 70 năm, nhưng ai là quân vương trị vì lâu thứ hai?"), ("I said it was c) Queen Victoria.", "Tôi đã nói đó là c) Queen Victoria.")]),
    ("Co-presenter", [("I'm glad you were so sure, because you were correct, Sam.", "Tôi mừng vì cô chắc chắn như vậy, vì cô đã đúng, Sam."), ("Victoria was queen for almost 64 years which is a long time, but not as long as Elizabeth.", "Victoria làm Nữ hoàng gần 64 năm, đó là một quãng thời gian dài, nhưng vẫn không dài bằng Elizabeth.")]),
    ("Presenter", [("OK, let's recap the vocabulary from this programme about the Queen's jubilee - a celebration of the anniversary of a special event, usually involving the Royal Family.", "Được rồi, hãy ôn lại từ vựng trong chương trình này về jubilee của Nữ hoàng - một lễ kỷ niệm ngày kỷ niệm của một sự kiện đặc biệt, thường liên quan đến Hoàng gia."), ("A king or queen's reign means the period of time they rule a country.", "Reign của vua hoặc nữ hoàng là khoảng thời gian họ cai trị một đất nước.")]),
    ("Co-presenter", [("A coronation is the ceremony at which someone is made monarch - the king or queen.", "Coronation là nghi lễ trong đó ai đó được phong làm quân vương - vua hoặc nữ hoàng."), ("Trifle is a popular pudding made of a layer of fruit and cake, a layer of custard, and a top layer of cream.", "Trifle là món pudding phổ biến gồm một lớp trái cây và bánh, một lớp sữa trứng, và lớp trên cùng là kem.")]),
    ("Presenter", [("If you say a food dish is a twist on something, you mean it's a variation of a traditional recipe, using new and exciting ingredients.", "Nếu nói một món ăn là a twist on something, tức là nó là một biến thể của công thức truyền thống, sử dụng những nguyên liệu mới và thú vị."), ("And finally, someone who is humble is modest, and not proud.", "Và cuối cùng, humble là người khiêm tốn, không kiêu ngạo.")]),
    ("Co-presenter", [("If you were inspired by this recipe, why not try making it.", "Nếu bạn thấy hứng thú với công thức này, sao không thử làm nó."), ("But that's all from us. Goodbye for now.", "Nhưng chương trình đến đây là hết. Tạm biệt bạn.")]),
    ("Presenter", [("Goodbye!", "Tạm biệt!")]),
]

for role, pairs in turns:
    body = "".join(p(en, vi) for en, vi in pairs)
    avatar = "R" if role == "Guest expert" else role[0]
    dialogue += f'<div class="dialogue-turn{" guest" if role == "Guest expert" else ""}"><div class="speaker-avatar neil">{avatar}</div><div class="dialogue-body"><p class="speaker-name">{role}</p>{body}</div></div>'

dialogue += '<div class="dialogue-turn recap"><div class="speaker-avatar neil">R</div><div class="dialogue-body"><p class="speaker-name">Presenter</p>' + p("Recap: a jubilee marks a special anniversary, a reign is the time a monarch rules, a coronation is the ceremony of becoming king or queen, a trifle is a layered pudding, a twist is a variation, and humble means modest.", "Ôn tập: jubilee là lễ kỷ niệm một dịp đặc biệt, reign là thời gian một quân vương trị vì, coronation là nghi lễ đăng quang, trifle là món pudding nhiều lớp, twist là một biến thể, và humble nghĩa là khiêm tốn.") + '</div></div>'
obj["sections"].append({"id": "dialogue", "title": "Bilingual Dialogue", "level": 1, "html": dialogue})

obj["sections"].append({"id": "speaking-1", "title": "Speaking Part 1", "level": 2, "html": '<div class="ielts-sub"><div class="ielts-sub-header"><span class="ielts-badge">Speaking Part 1</span><span class="ielts-sub-title">Sample question</span></div><div class="ielts-sub-body"><div class="question-block">Question: Do you enjoy watching royal events on television?</div>' + p("Yes, I do, because they often feel like part of a shared national <strong>jubilee</strong> mood.", "Có, tôi thích, vì chúng thường tạo cảm giác như một bầu không khí <strong>lễ kỷ niệm lớn</strong> chung của cả quốc gia.") + p("I also like learning the stories behind the celebrations, especially when they show how traditions change over time.", "Tôi cũng thích tìm hiểu các câu chuyện phía sau lễ mừng, nhất là khi chúng cho thấy truyền thống thay đổi theo thời gian.") + p("Events like a coronation or a parade can be impressive, but I am more interested in the cultural meaning.", "Những sự kiện như lễ đăng quang hay diễu hành có thể rất ấn tượng, nhưng tôi quan tâm hơn đến ý nghĩa văn hóa của chúng.") + p("Watching them can be relaxing too, because they create a calm and festive atmosphere.", "Xem chúng cũng giúp thư giãn, vì chúng tạo ra bầu không khí yên bình và lễ hội.") + "</div></div>"})

obj["sections"].append({"id": "speaking-2", "title": "Speaking Part 2", "level": 2, "html": '<div class="ielts-sub"><div class="ielts-sub-header"><span class="ielts-badge">Speaking Part 2</span></div><div class="ielts-sub-body"><div class="question-block">Cue card: Describe a celebration that brought people together.</div>' + p("One celebration that comes to mind is a street festival I saw in my neighbourhood.", "Một lễ hội tôi nhớ đến là lễ hội đường phố tôi từng thấy ở khu phố của mình.") + p("It had music, food stalls, and families chatting with neighbours they had not spoken to for months.", "Nó có âm nhạc, quầy đồ ăn và các gia đình trò chuyện với hàng xóm mà họ đã lâu không gặp.") + p("The atmosphere felt really <strong>contagious</strong>, because everyone seemed to smile at the same time.", "Không khí rất <strong>lan tỏa</strong>, vì ai cũng như cùng mỉm cười một lúc.") + p("What made it special was that people were not just consuming entertainment, they were participating together.", "Điều đặc biệt là mọi người không chỉ thưởng thức giải trí, họ còn cùng tham gia.") + p("That gave the event a sense of shared purpose and community pride.", "Điều đó mang lại cảm giác về mục đích chung và niềm tự hào cộng đồng.") + p("If I had to describe it in one phrase, I would call it a modern <strong>twist</strong> on a traditional gathering.", "Nếu phải mô tả bằng một cụm, tôi sẽ gọi đó là một <strong>biến tấu</strong> hiện đại của một buổi tụ họp truyền thống.") + "</div></div>"})

obj["sections"].append({"id": "speaking-3", "title": "Speaking Part 3", "level": 2, "html": '<div class="ielts-sub"><div class="ielts-sub-header"><span class="ielts-badge">Speaking Part 3</span></div><div class="ielts-sub-body"><div class="question-block">Question: Why do people enjoy national celebrations?</div>' + p("People enjoy them because they create a sense of belonging.", "Mọi người thích chúng vì chúng tạo ra cảm giác thuộc về.") + p("That matters especially in large societies, where daily life can feel fragmented.", "Điều đó đặc biệt quan trọng trong các xã hội lớn, nơi cuộc sống hằng ngày có thể bị phân mảnh.") + p("A celebration gives people a shared story, and that shared story can be emotionally powerful.", "Một lễ mừng cho mọi người một câu chuyện chung, và câu chuyện chung đó có thể rất mạnh về mặt cảm xúc.") + p("For example, a jubilee or coronation allows different generations to talk about the same event.", "Ví dụ, một jubilee hoặc coronation cho phép nhiều thế hệ khác nhau cùng nói về một sự kiện.") + p("As a result, these occasions can strengthen national memory and social connection.", "Kết quả là, những dịp này có thể củng cố ký ức quốc gia và sự gắn kết xã hội.") + "</div></div>"})

obj["sections"].append({"id": "patterns", "title": "Sentence Patterns", "level": 2, "html": '<div class="ielts-sub"><div class="ielts-sub-header"><span class="ielts-badge">Sentence Patterns</span><span class="ielts-sub-title">Band 7-8 structures from this episode</span></div><div class="ielts-sub-body"><div class="pattern-block"><p class="pattern-label">Pattern 1 - Explaining a variation with "a twist on"</p><p class="en pattern-formula">[Noun phrase] + is a twist on + [traditional noun phrase]</p>' + p('The Platinum Pudding is a <strong>twist on</strong> a classic British dessert.', 'Platinum Pudding là một <strong>biến tấu của</strong> món tráng miệng Anh cổ điển.') + p('Many modern dishes are a <strong>twist on</strong> familiar recipes.', 'Nhiều món ăn hiện đại là một <strong>biến tấu của</strong> các công thức quen thuộc.') + '</div><div class="pattern-block"><p class="pattern-label">Pattern 2 - Showing contrast with "not as... as"</p><p class="en pattern-formula">[Subject] + is not as + [adjective] + as + [comparison]</p>' + p("Victoria's reign was not as long as Elizabeth II's reign.", "Triều đại của Victoria không dài bằng triều đại của Elizabeth II.") + p("This dessert is not as complicated as it looks.", "Món tráng miệng này không phức tạp bằng vẻ ngoài của nó.") + '</div></div></div>'})

obj["sections"].append({"id": "writing", "title": "Writing Task 2", "level": 2, "html": '<div class="question-block">Some people think national celebrations are a waste of money. Others believe they are important for social unity. Discuss both views and give your opinion.</div>' + p("<strong>Thesis:</strong> Although celebrations can be expensive, I believe they are worthwhile when they strengthen shared identity and support local communities.", "<strong>Luận điểm:</strong> Mặc dù các lễ mừng có thể tốn kém, tôi cho rằng chúng đáng giá khi củng cố bản sắc chung và hỗ trợ cộng đồng địa phương.") + p("<strong>Model body paragraph:</strong> National celebrations often seem costly at first, but they can generate wider benefits. They bring people into public spaces, where they interact with neighbours and feel part of something larger than themselves. They can also support small businesses through food, travel, and event spending. In addition, well-designed celebrations preserve cultural memory and pass traditions to younger generations. For these reasons, the money spent is not simply a cost, but an investment in social cohesion. A jubilee, for example, can turn a historical event into a living public experience.", "<strong>Đoạn thân bài mẫu:</strong> Các lễ mừng quốc gia ban đầu thường có vẻ tốn kém, nhưng chúng có thể tạo ra lợi ích rộng hơn. Chúng đưa mọi người đến không gian công cộng, nơi họ tương tác với hàng xóm và cảm thấy mình là một phần của điều gì đó lớn hơn bản thân. Chúng cũng có thể hỗ trợ các doanh nghiệp nhỏ thông qua chi tiêu cho đồ ăn, đi lại và sự kiện. Ngoài ra, những lễ mừng được tổ chức tốt sẽ gìn giữ ký ức văn hóa và truyền thống cho thế hệ trẻ. Vì những lý do đó, số tiền chi ra không chỉ là chi phí, mà là một khoản đầu tư cho sự gắn kết xã hội. Chẳng hạn, một jubilee có thể biến một sự kiện lịch sử thành một trải nghiệm công cộng sống động.") + '</div>'})

obj["sections"].append({"id": "grammar", "title": "Grammar Band 7-8", "level": 1, "html": '<div class="grammar-card"><div class="grammar-card-header"><span class="grammar-num">1</span><span class="grammar-card-title">Hedging with may, might, and could</span></div><div class="grammar-row"><span class="grammar-row-label">Structure</span><div class="grammar-row-content structure-formula">Subject + may/might/could + base verb</div></div><div class="grammar-row"><span class="grammar-row-label">Explanation</span><div class="grammar-row-content">' + p("Use modal verbs to express possibility when you do not want to sound too certain.", "Dùng động từ khuyết thiếu để diễn tả khả năng khi bạn không muốn nói quá chắc chắn.") + '</div></div><div class="grammar-row"><span class="grammar-row-label">Example</span><div class="grammar-row-content">' + p("A royal celebration may bring people together.", "Một lễ mừng hoàng gia có thể gắn kết mọi người lại với nhau.") + '</div></div><div class="grammar-row"><span class="grammar-row-label">Speaking</span><div class="grammar-row-content">' + p("The event could be memorable because it involves many generations.", "Sự kiện này có thể đáng nhớ vì nó liên quan đến nhiều thế hệ.") + '</div></div><div class="grammar-row"><span class="grammar-row-label">Writing</span><div class="grammar-row-content">' + p("Public celebrations might strengthen social cohesion in the long term.", "Các lễ mừng công cộng có thể củng cố sự gắn kết xã hội về lâu dài.") + '</div></div><div class="grammar-row error-row"><span class="grammar-row-label">Incorrect</span><div class="grammar-row-content"><p class="en"><strong>Incorrect:</strong> The parade may brings people together.</p></div></div><div class="grammar-row"><span class="grammar-row-label">Corrected</span><div class="grammar-row-content">' + p("<strong>Corrected:</strong> The parade may bring people together.", "Sau may/might/could, dùng động từ nguyên mẫu.") + '</div></div></div>'})

obj["sections"].append({"id": "sources", "title": "Sources & Disclaimer", "level": 1, "html": '<p class="en">Official sources: BBC Learning English episode page and BBC transcript PDF at the links above. This lesson uses the original transcript for study purposes and includes Vietnamese translation for practice.</p><p class="vi">Nguồn chính thức: trang BBC Learning English và file PDF transcript BBC ở các liên kết phía trên. Bài học này dùng bản ghi gốc cho mục đích học tập và có bản dịch tiếng Việt để luyện tập.</p>'})

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(obj, f, ensure_ascii=False, indent=2)
print(out_path)
